Addversion: '3.4'
services:
  db-sql:
    image: niksob/my-mood-tracker:db-sql-1.0.0
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '9196:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      #      MYSQL_USER: server_user
      #      MYSQL_PASSWORD: iosk2LV4gh
      MYSQL_ROOT_PASSWORD: jkr367sk9Kn
      MYSQL_DATABASE: mood_tracker_db

  adminer-sql:
    image: adminer
    restart: always
    ports:
      - '9197:8080'

  db-service-cache:
    image: niksob/my-mood-tracker:db-redis-cache-1.0.0
    restart: always
    ports:
      - '9003:6379'
    command:
      - 'redis-server'
      - '--maxmemory 2gb'
      - '--maxmemory-policy allkeys-random'

  auth-service-cache:
    image: niksob/my-mood-tracker:auth-redis-cache-1.0.0
    restart: always
    ports:
      - '9004:6379'
    command:
      - 'redis-server'
      - '--maxmemory 2gb'
      - '--maxmemory-policy allkeys-random'

volumes:
  db_data: