version: '3.4'
services:
  db-sql:
    image: niksob/my-mood-tracker:db-sql-1.0.0
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - db-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      #      MYSQL_USER: server_user
      #      MYSQL_PASSWORD: iosk2LV4gh
      MYSQL_ROOT_PASSWORD: jkr367sk9Kn
      MYSQL_DATABASE: mood_tracker_db

  adminer-sql:
    image: adminer
    restart: always
    ports:
      - '9197:8080'
    networks:
      - db-network

  db-service-cache:
    image: niksob/my-mood-tracker:db-redis-cache-1.0.0
    restart: always
    networks:
      - db-network
    command:
      - 'redis-server'
      - '--maxmemory 2gb'
      - '--maxmemory-policy allkeys-random'

  auth-service-cache:
    image: niksob/my-mood-tracker:auth-redis-cache-1.0.0
    restart: always
    networks:
      - auth-network
    command:
      - 'redis-server'
      - '--maxmemory 2gb'
      - '--maxmemory-policy allkeys-random'

  config-service:
    image: niksob/my-mood-tracker:config-service-1.0.0
    restart: always
    networks:
      - db-network
      - auth-network
      - gateway-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9191/database_service/default" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      SPRING_PROFILES_ACTIVE: prod,native

  db-service:
    image: niksob/my-mood-tracker:database-service-1.0.0
    restart: always
    networks:
      - db-network
      - auth-network
      - gateway-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  auth-service:
    image: niksob/my-mood-tracker:authorization-service-1.0.0
    restart: always
    networks:
      - auth-network
      - gateway-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  mail-sender:
    image: niksob/my-mood-tracker:mail-sender-1.0.0
    restart: always
    networks:
      - auth-network
      - gateway-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

  gateway-service:
    image: niksob/my-mood-tracker:gateway-service-1.0.0
    restart: always
    ports:
      - '8082:8082'
    networks:
      - gateway-network
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  db_data:

networks:
  db-network:
    driver: bridge
  auth-network:
    driver: bridge
  gateway-network:
    driver: bridge