spring:
  application:
    name: mail-sender
  config:
    import:
      - configserver:http://localhost:9191/mail-sender-connection

  mail:
    debug: false
    host: smtp.yandex.ru
    username: moodtracker@yandex.ru
    password: fox5aq-dekJe1-gahkiw
    port: 465
    protocol: smtps

server:
  address: ${microservice.connection.mail-sender.hostname}
  port: ${microservice.connection.mail-sender.port}
  servlet:
    context-path: ${microservice.connection.mail-sender.path}