### GET Request
GET http://localhost:8082/api/mood_tag?user_id=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUX1VTRVJOQU1FIiwiZXhwIjoxNzEzNDUxNjkxLCJkZXYiOiJURVNUX0RFVklDRSIsInVzZXJJZCI6IjQifQ.2UtYFuejrUEw8V0aMwS-kz9aLCPd6moZE_4sf0qzePA3kuMEXqTmXYb-DUknDwCHgukww2XAuw42_FemjKA1wQ

### POST Request
POST http://localhost:8082/api/mood_tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUX1VTRVJOQU1FIiwiZXhwIjoxNzEzNDUxNjkxLCJkZXYiOiJURVNUX0RFVklDRSIsInVzZXJJZCI6IjQifQ.2UtYFuejrUEw8V0aMwS-kz9aLCPd6moZE_4sf0qzePA3kuMEXqTmXYb-DUknDwCHgukww2XAuw42_FemjKA1wQ

{
  "name": "home",
  "degree": 3,
  "userId": 4
}

### PUT Request
PUT http://localhost:8082/api/mood_tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUX1VTRVJOQU1FIiwiZXhwIjoxNzEzNDUxNjkxLCJkZXYiOiJURVNUX0RFVklDRSIsInVzZXJJZCI6IjQifQ.2UtYFuejrUEw8V0aMwS-kz9aLCPd6moZE_4sf0qzePA3kuMEXqTmXYb-DUknDwCHgukww2XAuw42_FemjKA1wQ

{
  "id": 6,
  "name": "home",
  "degree": 0,
  "userId": 4
}

### DELETE Request
DELETE http://localhost:8082/api/mood_tag?id=6&user_id=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUX1VTRVJOQU1FIiwiZXhwIjoxNzEzNDUxNjkxLCJkZXYiOiJURVNUX0RFVklDRSIsInVzZXJJZCI6IjQifQ.2UtYFuejrUEw8V0aMwS-kz9aLCPd6moZE_4sf0qzePA3kuMEXqTmXYb-DUknDwCHgukww2XAuw42_FemjKA1wQ