### GET Request
GET http://localhost:8082/api/mood_tag?user_id=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWtpdG9zMDAyM0BnbWFpbC5jb20iLCJleHAiOjE3MTM1MjU4NjgsInVzZXJJZCI6IjQiLCJkZXYiOiJURVNUX0RFVklDRSJ9.N09drnTiUzPuQOcPzeh4vVzHxrEd5h8-HBmmSL57sA7H16Fz34eaQITGuHbMHmljhGs9opjjXklUAxW613fABw

### POST Request
POST http://localhost:8082/api/mood_tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWtpdG9zMDAyM0BnbWFpbC5jb20iLCJleHAiOjE3MTM1MjU4NjgsInVzZXJJZCI6IjQiLCJkZXYiOiJURVNUX0RFVklDRSJ9.N09drnTiUzPuQOcPzeh4vVzHxrEd5h8-HBmmSL57sA7H16Fz34eaQITGuHbMHmljhGs9opjjXklUAxW613fABw

{
  "name": "home",
  "degree": 3,
  "userId": 4
}

### PUT Request
PUT http://localhost:8082/api/mood_tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWtpdG9zMDAyM0BnbWFpbC5jb20iLCJleHAiOjE3MTM1MjU4NjgsInVzZXJJZCI6IjQiLCJkZXYiOiJURVNUX0RFVklDRSJ9.N09drnTiUzPuQOcPzeh4vVzHxrEd5h8-HBmmSL57sA7H16Fz34eaQITGuHbMHmljhGs9opjjXklUAxW613fABw

{
  "id": 6,
  "name": "home",
  "degree": 0,
  "userId": 4
}

### DELETE Request
DELETE http://localhost:8082/api/mood_tag?id=6&user_id=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWtpdG9zMDAyM0BnbWFpbC5jb20iLCJleHAiOjE3MTM1MjU4NjgsInVzZXJJZCI6IjQiLCJkZXYiOiJURVNUX0RFVklDRSJ9.N09drnTiUzPuQOcPzeh4vVzHxrEd5h8-HBmmSL57sA7H16Fz34eaQITGuHbMHmljhGs9opjjXklUAxW613fABw