### GET Request
GET http://80.242.58.161:8082/api/mood_entry?start_date=2024-04-01&end_date=2024-04-18
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWsiLCJleHAiOjE3MTY4ODg4NzQsImRldiI6IlRFU1RfREVWSUNFIiwidXNlcklkIjoiMSJ9._UsjZqwPPFHwl77vgY3LU2HP55hBTkGpzMYCuej2sLjgUR7SCQyfWxA_BeTSCc_9J_b7nKj29L2-uz1u6AEdpw

### POST Request
POST http://80.242.58.161:8082/api/mood_entry
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWsiLCJleHAiOjE3MTY4ODg4NzQsImRldiI6IlRFU1RfREVWSUNFIiwidXNlcklkIjoiMSJ9._UsjZqwPPFHwl77vgY3LU2HP55hBTkGpzMYCuej2sLjgUR7SCQyfWxA_BeTSCc_9J_b7nKj29L2-uz1u6AEdpw

{
  "degree": 1,
  "date_time": "2024-05-28T11:23:51",
  "mood_tags": [
    {
      "id": 8,
      "name": "home",
      "degree": 3
    },
    {
      "name": "sleep",
      "degree": 0
    }
  ]
}

### PUT Request
PUT http://80.242.58.161:8082/api/mood_entry
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWsiLCJleHAiOjE3MTY4ODg4NzQsImRldiI6IlRFU1RfREVWSUNFIiwidXNlcklkIjoiMSJ9._UsjZqwPPFHwl77vgY3LU2HP55hBTkGpzMYCuej2sLjgUR7SCQyfWxA_BeTSCc_9J_b7nKj29L2-uz1u6AEdpw

{
  "id": 3,
  "degree": 3,
  "date_time": "2024-05-28T12:01:02",
  "mood_tags": [
    {
      "name": "impro",
      "degree": 3
    },
    {
      "id": 9,
      "name": "sleep",
      "degree": 1
    },
    {
      "name": "friends",
      "degree": 4
    }
  ]
}


### DELETE Request
DELETE http://80.242.58.161:8082/api/mood_entry?id=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWsiLCJleHAiOjE3MTY4ODg4NzQsImRldiI6IlRFU1RfREVWSUNFIiwidXNlcklkIjoiMSJ9._UsjZqwPPFHwl77vgY3LU2HP55hBTkGpzMYCuej2sLjgUR7SCQyfWxA_BeTSCc_9J_b7nKj29L2-uz1u6AEdpw