### GET Request
GET http://localhost:8092/api/service/auth/signout?userId=4&device=TEST_DEVICE

### GET Request
GET http://localhost:8092/api/service/auth/signout/all?user_id=4

### Signup request
POST http://localhost:8092/api/service/auth/signup
Content-Type: application/json

{
  "email": "TEST_PASSWORD@mail.com",
  "username": "TEST_USERNAME",
  "password": "TEST_PASSWORD"
}

### Signup confirmation
GET http://localhost:8092/api/service/auth/signup/activate?active_code=79243918-f942-4feb-81cf-156859143140

### Reset password
POST http://localhost:8092/api/service/auth/reset/password
Content-Type: application/json

{
  "user_id":  "1",
  "old_password":  "TEST_PASSWORD",
  "new_password":  "SECRET"
}