### GET Request
GET http://localhost:8092/api/service/auth/signout?userId=4&device=TEST_DEVICE

### GET Request
GET http://localhost:8092/api/service/auth/signout/all?user_id=4

### POST Request
POST http://localhost:8092/api/service/auth/signup
Content-Type: application/json

{
  "username": "TEST_USERNAME",
  "password": "TEST_PASSWORD"
}
