### GET Request
GET http://localhost:8081/api/service/user?username=MY_TEST_USERNAME

### GET Request
GET http://localhost:8081/api/service/user?username=THROW

### POST Request
POST http://localhost:8081/api/service/user
Content-Type: application/json

{
  "username": "TEST_USERNAME",
  "nickname": "TEST_NICKNAME",
  "password": "TEST_PASSWORD"
}

### POST Request
POST http://localhost:8081/api/service/user
Content-Type: application/json

{
  "username": "TEST_USERNAME",
  "nickname": "TEST_NICKNAME",
  "password": "0000"
}

