spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///service_configs

repo:
  remote:
    git:
      uri: https://github.com/nikitasob23/my-mood-tracker-config.git
      username: nikitasob23
      password: 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
      properties-file: merge_properties
  local:
    git:
      path: /git_configs
    config:
      path: /service_configs