server:
  port: 9191
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///Users/nickworker/Documents/Repo/my-mood-tracker-server/domain/src/main/resources/common-config
            - file:///Users/nickworker/Documents/Repo/my-mood-tracker-server/database-service/src/main/resources/common-config
            - file:///Users/nickworker/Documents/Repo/my-mood-tracker-server/authorization-service/src/main/resources/common-config