repo:
  remote:
    git:
      uri: https://github.com/nikitasob23/my-mood-tracker-config.git
      username: nikitasob23
      password: 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
      properties-file: merge_properties
  local:
    git:
      path: app/git_configs
    config:
      path: app/service_configs

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///${repo.local.config.path}
